[versions]
agp = "8.9.1"
appcompatVersion = "1.1.0"
avatarviewCoil = "1.0.4"
avvylib = "1.2.0"
ccp = "2.7.3"
compiler = "4.13.0"
glide = "4.16.0"
gson = "2.10.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.1"
navigationFragment = "2.8.9"
navigationUi = "2.8.9"
pinview = "1.4.3"
pinviewVersion = "1.4.4"
superiorToasts = "v1.0"

[libraries]
appcompat-v110 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
avatarview-coil = { module = "io.getstream:avatarview-coil", version.ref = "avatarviewCoil" }
avvylib = { module = "xyz.schwaab:avvylib", version.ref = "avvylib" }
ccp = { module = "com.hbb20:ccp", version.ref = "ccp" }
chaosleung-pinview = { module = "io.github.chaosleung:pinview", version.ref = "pinviewVersion" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
pinview = { module = "com.chaos.view:pinview", version.ref = "pinview" }
superior-toasts = { module = "com.github.shubh420:Superior-Toasts", version.ref = "superiorToasts" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

